package com.nicholasbergesen.gunsout.ui.theme

import androidx.compose.ui.graphics.Color

object GunsoutPalette {
    val CrimsonDark = Color(0xFFDC2626)
    val CrimsonLight = Color(0xFFB91C1C)
    val CrimsonSoft = Color(0xFFFECACA)
    val CrimsonDeep = Color(0xFF7F1D1D)
    val CrimsonError = Color(0xFFF87171)

    val GunMetalBackground = Color(0xFF1A1C20)
    val GunMetalBackgroundEnd = Color(0xFF141519)
    val GunMetalSurface = Color(0xFF23262C)
    val GunMetalSurfaceVariant = Color(0xFF2D3138)
    val GunMetalSurfaceContainer = Color(0xFF2A2D34)
    val GunMetalAccentCard = Color(0xFF2A1416)
    val GunMetalLine = Color(0xFF34373F)
    val GunMetalCardBorder = Color(0xFF2E323A)
    val SteelOutline = Color(0xFF3F434B)
    val SteelSecondary = Color(0xFF4B5563)
    val IceText = Color(0xFFE5E7EB)
    val MutedText = Color(0xFF9CA3AF)

    val PewterBackground = Color(0xFFECEDF0)
    val PewterSurface = Color(0xFFF5F6F8)
    val PewterSurfaceVariant = Color(0xFFE0E2E6)
    val PewterOutline = Color(0xFFB6BAC1)
    val InkText = Color(0xFF1A1C20)
    val SlateText = Color(0xFF4B5563)

    val CleanBackground = Color(0xFFF6F7F9)
    val CleanText = Color(0xFF111827)
    val CleanMuted = Color(0xFF6B7280)
    val CleanAccent = Color(0xFF4F46E5)
    val CleanCard = Color(0xFFFFFFFF)
    val CleanLine = Color(0xFFECEEF1)
    val CleanChip = Color(0xFFEEF0FB)

    val NeoBackground = Color(0xFFFEF9E7)
    val NeoText = Color(0xFF0A0A0A)
    val NeoMuted = Color(0xFF52525B)
    val NeoAccent = Color(0xFFEF4444)
    val NeoCard = Color(0xFFFFFFFF)
    val NeoAccentCard = Color(0xFFFDE047)
    val NeoTrack = Color(0xFFE4E4E7)

    val GlassBackgroundStart = Color(0xFF0EA5E9)
    val GlassBackgroundMid = Color(0xFF0B1437)
    val GlassBackgroundEnd = Color(0xFF020617)
    val GlassText = Color(0xFFF0F9FF)
    val GlassMuted = Color(0xA6E0F2FE)
    val GlassAccent = Color(0xFF22D3EE)
    val GlassOnAccent = Color(0xFF04222B)
    val GlassCard = Color(0x14FFFFFFL)
    val GlassAccentCard = Color(0x2422D3EEL)
    val GlassLine = Color(0x24FFFFFFL)
    val GlassBorder = Color(0x29FFFFFFL)
    val GlassChip = Color(0x1FFFFFFFL)
    val GlassTrack = Color(0x2EFFFFFFL)

    val SoftBackgroundStart = Color(0xFFFFF7F3)
    val SoftBackgroundEnd = Color(0xFFF0FDFA)
    val SoftText = Color(0xFF334155)
    val SoftMuted = Color(0xFF94A3B8)
    val SoftAccent = Color(0xFF14B8A6)
    val SoftAccentDark = Color(0xFF0F766E)
    val SoftCard = Color(0xFFFFFFFF)
    val SoftAccentCardStart = Color(0xFFCCFBF1)
    val SoftAccentCardEnd = Color(0xFFFDE4D8)
    val SoftLine = Color(0xFFEEF2F5)
    val SoftChip = Color(0xFFE6FBF6)
    val SoftTrack = Color(0xFFE2E8F0)

    val VibrantBackgroundStart = Color(0xFF2B1055)
    val VibrantBackgroundMid = Color(0xFF7B2FF7)
    val VibrantBackgroundEnd = Color(0xFFF72585)
    val VibrantText = Color(0xFFFDF4FF)
    val VibrantMuted = Color(0xB3FDF4FF)
    val VibrantAccent = Color(0xFFFF4D97)
    val VibrantCard = Color(0x1FFFFFFFL)
    val VibrantAccentCard = Color(0x2EFFFFFFL)
    val VibrantLine = Color(0x33FFFFFFL)
    val VibrantBorder = Color(0x2EFFFFFFL)
    val VibrantChip = Color(0x29FFFFFFL)
    val VibrantTrack = Color(0x38FFFFFFL)
}
